name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - tts

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    environment: daily-news

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone TTS repo
      run: |
        git clone https://github.com/coqui-ai/TTS.git TTS

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION  }}

    # Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    # Build and push image
    - name: Build, tag, and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/${{ secrets.ECR_REPO }}:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/${{ secrets.ECR_REPO }}:$IMAGE_TAG $ECR_REGISTRY/${{ secrets.ECR_REPO }}:latest
        
        docker push $ECR_REGISTRY/${{ secrets.ECR_REPO }}:$IMAGE_TAG
        docker push $ECR_REGISTRY/${{ secrets.ECR_REPO }}:latest